# Generated by Django 5.0.1 on 2024-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=0, max_length=100, verbose_name='Чат ID'),
        ),
    ]
