version: '3'

services:
  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis
    ports:
      - '6380:6379'

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8001:8000'
    healthcheck:
      test: "curl --fail http://127.0.0.1:8000/swagger/"
      interval: 5s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
