# Generated by Django 5.0.1 on 2024-01-29 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=1000, verbose_name='Место выполнения привычки')),
                ('action_time', models.DateTimeField(verbose_name='Время действия')),
                ('action', models.CharField(max_length=1000, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[('Каждый день', 1), ('Через день', 2), ('Через два дня', 3), ('Через три дня', 4), ('Через четыре дня', 5), ('Через пять дней', 6), ('Раз в неделю', 7)], default='Каждый день', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность')),
                ('reward', models.CharField(max_length=500, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на исполнение привычки, сек')),
                ('is_public', models.BooleanField(default=False, verbose_name='Открыта для всех')),
                ('associated_with', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pleasant', to='habits_app.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
