# Generated by Django 5.0.1 on 2024-02-08 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0006_alter_habit_periodicity_alter_habit_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('associated_with__isnull', True), ('is_pleasant', True), ('reward__isnull', True)), models.Q(('associated_with__isnull', False), ('is_pleasant', False), ('reward__isnull', True)), models.Q(('associated_with__isnull', True), ('is_pleasant', False), ('reward__isnull', False)), _connector='OR'), name='is_pleasant_or_reward_or_associated'),
        ),
    ]
