# Generated by Django 5.0.1 on 2024-02-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0008_alter_habit_associated_with'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='is_pleasant_or_reward_or_associated',
        ),
    ]
