# Generated by Django 4.2.10 on 2024-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0010_alter_habit_associated_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время действия'),
        ),
    ]
