# Generated by Django 4.2.10 on 2024-02-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0011_alter_habit_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='associated_with',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleasant', to='habits_app.habit', verbose_name='Связанная приятная привычка'),
        ),
    ]
